config/routes.rb
Rails.application.routes.draw do

  resources :candidates, only: [:index, :new, :create, :show]
  get 'pspost', to: 's3#new'
  get 'thankyou', to: 'welcome#thankyou'
  root 'candidates#new'
  post '/', to: 'candidates#new'

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  validates_presence_of :name, :gender, :experience, :position, :area, :email, :phone
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

  after_action :allow_iframe

  def index
    @candidate = Candidate.new
    render 'new'
  end

  def new
    @candidate = Candidate.new
  end

  def create
    @candidate = Candidate.new(candidate_params)

    if @candidate.save
      CandidateMailer.welcome_email(@candidate).deliver
      CandidateMailer.notification_email(@candidate).deliver
      render "welcome/thankyou" 
    else
      render 'new'
    end
  end

  def show
    # @candidate = Candidate.find(params[:id])
    @candidate = Candidate.new
    render 'new'
  end

  private
    def candidate_params
      params.require(:candidate).permit(:name, :gender, :experience, :position, :area, :email, :phone, :resume)
    end

    def allow_iframe
      response.headers.except! 'X-Frame-Options'
    end
end

app/controllers/s3_controller.rb
class S3Controller < ApplicationController
  
  after_action :allow_iframe

  def new
    random_id = SecureRandom.uuid
    s3data = S3_BUCKET.presigned_post(
      key: "uploads/#{random_id}/${filename}",
      success_action_status: 201,
      acl: :public_read
    )
    render json: { fields: s3data.fields, url: s3data.url, directory: random_id }
  end

  private
    
    def allow_iframe
      response.headers.except! 'X-Frame-Options'
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  after_action :allow_iframe
  
  def index

  end

  def thankyou
    render 'thankyou'
  end

  private

    def allow_iframe
      response.headers.except! 'X-Frame-Options'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
  def position_options
    [
      ['Store Manager'],
      ['Departmental Manager'],
      ['Salesperson'],
      ['Cashier'],
      ['Buyer/Merchandiser'],
      ['Marketer']
    ]
  end

  def area_options
    [
      ['Central Region'],
      ['Western Region'],
      ['Eastern Region']
    ]
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/candidates/_form.html.erb
<div class="candidate_form">
  <%= form_for @candidate, :html => {:class => 'form-horizontal new_candidate'} do |f| %>

    <% if @candidate.errors.any? %>
      <div class="errors">
        <h4 class="text-danger"><%= pluralize(@candidate.errors.count, "error") %> prohibited your form being saved</h4>
        <ul class="text-danger list-inline">
          <% @candidate.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="form-group">
      <div class="col-xs-4 control-label">
        <%= f.label :name %>
      </div>
      <div class="col-xs-8 no-padding">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-xs-4 control-label">
        <%= f.label :gender %>
      </div>
      <div class="col-xs-8 no-padding field-wrap" style="padding-top: 8px;">
        <div class="col-xs-4 col-xs-offset-1 radio">
          <%= f.radio_button :gender, "male", :checked => true %>
          <%= f.label :gender_male, "Male" %>
        </div>
        <div class="col-xs-6 no-padding radio">
          <%= f.radio_button :gender, "female" %>
          <%= f.label :gender_female, "Female" %>
        </div>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-xs-4 control-label">
        <%= f.label :experience %>
      </div>
      <div class="col-xs-8 no-padding">
        <%= f.select :experience, options_for_select((0..30).step(1)), {include_blank: "Please select"} ,{:class => 'form-control'} %>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-xs-4 control-label">
        <%= f.label :position %>
      </div>
      <div class="col-xs-8 no-padding">
        <%= f.select :position, options_for_select(position_options), {include_blank: "Please select"}, {:class => 'form-control'} %>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-xs-4 control-label">
        <%= f.label :area %>
      </div>
      <div class="col-xs-8 no-padding">
        <%= f.select :area, options_for_select(area_options), {include_blank: "Please select"}, {:class => 'form-control'} %>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-xs-4 control-label">
        <%= f.label :email %>
      </div>
      <div class="col-xs-8 no-padding">
        <%= f.email_field :email, class: 'form-control' %>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-xs-4 control-label">
        <%= f.label :phone %>
      </div>
      <div class="col-xs-8 no-padding">
        <%= f.phone_field :phone, class: 'form-control' %>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-xs-4 control-label">
        <%= f.label :resume %>
      </div>
      <div class="col-xs-8 no-padding" style="position: relative; padding-top: 9px; height: 50px;">
        <span class="btn btn-success fileinput-button">
          <i class="glyphicon glyphicon-plus"></i>
          <span>Select files...</span>
          <%= f.file_field :resume %>
        </span>
        <span class="output-msg"></span>
      </div>
    </div>

    <div class="form-group submit-wrap">
      <%= f.submit "Apply", class: "btn btn-success btn-block btn-submit" %>
    </div>

  <% end %>
</div>

app/views/candidates/index.html.erb
<h1 class="text-center text-white">Candidates</h1>
<p class="text-center text-white lead"><%= link_to 'Apply', new_candidate_path %></p>

app/views/candidates/new.html.erb
<h1 class="text-center">We are M&S, are you?</h1>

<p class="text-left lead">With our unique approach to style and service, we’re focused
on growing into a market-leading international fashion brand
which means exciting opportunities, greater responsibility,
excellent training, a clear development path. The perfect career move.
</p>

<p class="text-left lead">To apply please fill in your details below and attach a CV if you have one. The recruitment manager will contact you shortly.</p>

<%= render 'form' %>

<p class="text-center" style="margin-bottom: 0;">For more information, please email <strong><%= mail_to "mnshayat@alhokair.com.sa", "mnshayat@alhokair.com.sa", subject: "M&S Job Application" %></strong></p>

app/views/candidates/show.html.erb
<h1 class="text-center text-white">Show Candidate</h1>
<p class="text-center text-white lead">Thanks, <%= @candidate.first_name %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MsRecruitment</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script src="//use.typekit.net/qbx8hcs.js"></script>
    <script>try{Typekit.load();}catch(e){}</script>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="content_wrapper col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
          <h1 class="brand"><%= image_tag 'brand.png' %></h1>
          <%= yield %>
        </div>
      </div>
    </div>
    <%= debug(params) if Rails.env.development? %>
    <div class="session"></div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1 class="text-center text-white">We are M&S, are you?</h1>

<p class="lead text-center text-white" style="margin-top:30px">
  <%= link_to 'Apply for a job', 
    new_candidate_path, html_options = {:class => "btn btn-outline btn-lg"} 
  %>
</p>

app/views/welcome/thankyou.html.erb
<h1 class="text-center text-white">Thank you for your application</h1>
<p class="lead text-center text-white">If you application is successful we will be in touch shortly</p>